[package]
name = "started"
version = "0.1.0"
authors = ["DianaSensei <43933486+DianaSensei@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.9.0"
actix-web = "2.0"
actix-rt = "1.1.1"
dotenv = "0.15"
listenfd = "0.3"
env_logger = "0.7.1"
actix-cors = "0.2.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
lazy_static ="1.4"
derive_more ="0.99.9"
chrono = {version = "0.4", features=["serde"]}
envy = "0.4"
log = "0.4.11"
futures = "0.3.5"
uuid = {version = "0.8.1", features = ["serde", "v4"]}
diesel = { version = "1.4.5", features = ["chrono", "postgres", "r2d2", "uuidv07"] }